from typing import Dict, Any, List
import json
from datetime import datetime
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import base64
from email.mime.text import MIMEText

from app.api.auth import get_user_by_id
from app.services.google_auth import refresh_google_credentials
from app.models.meeting import MeetingAction, ActionStatus


class ActionExecutor:
    """Executes actions generated by the AI agent using Google APIs"""
    
    def __init__(self, user_id: str):
        self.user_id = user_id
        self.user = None
        self.credentials = None
    
    async def _initialize(self):
        """Initialize user and credentials asynchronously"""
        if not self.user:
            self.user = await get_user_by_id(self.user_id)
            self.credentials = await self._get_credentials()
    
    async def _get_credentials(self) -> Credentials:
        """Get Google credentials for the user"""
        if not self.user or not self.user.google_tokens:
            raise Exception("Google authentication required")
        
        if self.user.google_tokens.get("refresh_token"):
            return refresh_google_credentials(self.user.google_tokens["refresh_token"])
        
        return Credentials(
            token=self.user.google_tokens.get("access_token"),
            refresh_token=self.user.google_tokens.get("refresh_token"),
            token_uri=self.user.google_tokens.get("token_uri"),
            client_id=self.user.google_tokens.get("client_id"),
            client_secret=self.user.google_tokens.get("client_secret"),
            scopes=self.user.google_tokens.get("scopes")
        )
    
    async def execute_action(self, action: MeetingAction) -> Dict[str, Any]:
        """Execute a single action based on its type"""
        try:
            # Initialize user and credentials
            await self._initialize()
            
            function_name = action.details.get("function")
            arguments = action.details.get("arguments", {})
            
            # Map function names to execution methods
            executors = {
                "schedule_calendar_event": self._execute_calendar_event,
                "send_email": self._execute_send_email,
                "update_google_sheet": self._execute_update_sheet,
                "create_google_doc": self._execute_create_google_doc,
                "create_todo": self._execute_create_todo
            }
            
            executor = executors.get(function_name)
            if not executor:
                raise Exception(f"Unknown function: {function_name}")
            
            # Execute the action
            result = await executor(arguments)
            
            # Update action status
            action.status = ActionStatus.EXECUTED
            action.executed_at = datetime.utcnow()
            
            return {
                "success": True,
                "result": result,
                "action_id": action.id
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "action_id": action.id
            }
    
    async def _execute_calendar_event(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """Create a Google Calendar event"""
        print(f"📅 Creating Google Calendar event: {args.get('title')}")
        print(f"   Start time: {args.get('start_time')}")
        print(f"   End time: {args.get('end_time')}")
        print(f"   Attendees: {args.get('attendees', [])}")
        
        # Validate dates are in the future
        from datetime import datetime
        start_time_str = args.get('start_time')
        try:
            start_time = datetime.fromisoformat(start_time_str.replace('Z', '+00:00'))
            current_time = datetime.utcnow()
            
            if start_time < current_time:
                print(f"⚠️  Warning: Event start time {start_time_str} is in the past!")
                print(f"   Current time: {current_time.isoformat()}Z")
                # You might want to adjust to a future date or raise an error
                # For now, we'll log but still create the event
        except Exception as e:
            print(f"⚠️  Could not validate date: {e}")
        
        service = build('calendar', 'v3', credentials=self.credentials)
        
        # Get the user's calendar timezone
        try:
            calendar_service = service.calendars().get(calendarId='primary').execute()
            calendar_timezone = calendar_service.get('timeZone', 'UTC')
            print(f"📍 User's calendar timezone: {calendar_timezone}")
        except:
            calendar_timezone = 'UTC'
            print("⚠️  Could not get calendar timezone, using UTC")
        
        # Format datetime with timezone
        start_time = args.get('start_time')
        end_time = args.get('end_time')
        
        # Ensure datetime format includes timezone
        if start_time and not start_time.endswith('Z') and '+' not in start_time and '-' not in start_time[-6:]:
            # No timezone specified, add Z for UTC
            start_time = f"{start_time}Z"
        if end_time and not end_time.endswith('Z') and '+' not in end_time and '-' not in end_time[-6:]:
            # No timezone specified, add Z for UTC
            end_time = f"{end_time}Z"
        
        event = {
            'summary': args.get('title'),
            'description': args.get('description', ''),
            'start': {
                'dateTime': start_time,
                'timeZone': calendar_timezone,
            },
            'end': {
                'dateTime': end_time,
                'timeZone': calendar_timezone,
            },
            'attendees': [{'email': email} for email in args.get('attendees', [])]
        }
        
        result = service.events().insert(calendarId='primary', body=event).execute()
        
        print(f"✅ Calendar event created successfully!")
        print(f"   Event ID: {result.get('id')}")
        print(f"   Event link: {result.get('htmlLink')}")
        
        return {
            "event_id": result.get('id'),
            "event_link": result.get('htmlLink'),
            "status": result.get('status')
        }
    
    async def _execute_send_email(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """Send an email via Gmail"""
        service = build('gmail', 'v1', credentials=self.credentials)
        
        message = MIMEText(args.get('body', ''))
        message['to'] = ', '.join(args.get('to', []))
        message['subject'] = args.get('subject', '')
        
        raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
        
        result = service.users().messages().send(
            userId='me',
            body={'raw': raw}
        ).execute()
        
        return {
            "message_id": result.get('id'),
            "thread_id": result.get('threadId')
        }
    
    async def _execute_update_sheet(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """Update a Google Sheet"""
        service = build('sheets', 'v4', credentials=self.credentials)
        
        result = service.spreadsheets().values().update(
            spreadsheetId=args.get('sheet_id'),
            range=args.get('range'),
            valueInputOption='USER_ENTERED',
            body={'values': args.get('values', [])}
        ).execute()
        
        return {
            "updated_cells": result.get('updatedCells', 0),
            "updated_rows": result.get('updatedRows', 0),
            "updated_columns": result.get('updatedColumns', 0)
        }
    
    async def _execute_create_todo(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """Create a todo item in Google Tasks"""
        print(f"✅ Creating Todo task: {args.get('title')}")
        print(f"   Description: {args.get('description', 'No description')}")
        print(f"   Due date: {args.get('due_date', 'No due date')}")
        print(f"   Priority: {args.get('priority', 'Normal')}")
        
        try:
            # Use Google Tasks API
            service = build('tasks', 'v1', credentials=self.credentials)
            
            # Create task body
            task = {
                'title': args.get('title'),
                'notes': args.get('description', ''),
            }
            
            # Add due date if provided
            due_date = args.get('due_date')
            if due_date:
                # Google Tasks expects RFC 3339 date format
                # If we get a date like "2025-07-22", convert to proper format
                try:
                    if 'T' not in due_date:
                        # It's just a date, add time component
                        due_date = f"{due_date}T00:00:00.000Z"
                    elif not due_date.endswith('Z'):
                        # Add Z if missing
                        due_date = f"{due_date}Z"
                    task['due'] = due_date
                except Exception as e:
                    print(f"⚠️  Error formatting due date: {e}")
            
            # Insert task into default task list
            result = service.tasks().insert(
                tasklist='@default',
                body=task
            ).execute()
            
            print(f"✅ Todo created successfully in Google Tasks!")
            print(f"   Task ID: {result.get('id')}")
            print(f"   Task link: {result.get('selfLink')}")
            
            return {
                "todo_id": result.get('id'),
                "title": result.get('title'),
                "created": True,
                "google_task_id": result.get('id'),
                "status": result.get('status')
            }
            
        except Exception as e:
            print(f"❌ Failed to create Google Task: {e}")
            print(f"   Falling back to local todo creation")
            
            # Fallback to local implementation
            todo_id = f"todo_{datetime.utcnow().timestamp()}"
            
            return {
                "todo_id": todo_id,
                "title": args.get('title'),
                "created": True,
                "error": f"Google Tasks API error: {str(e)}",
                "fallback": True
            }
    
    async def _execute_create_google_doc(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """Create a Google Doc (for demo, just return success)"""
        # In a real implementation, this would use Google Docs API
        # to create a document with the meeting notes
        return {
            "doc_id": f"doc_{datetime.utcnow().timestamp()}",
            "title": args.get('title'),
            "content": args.get('content'),
            "created": True
        }


class OpenAIToolExecutor:
    """Handles OpenAI function calling format and execution"""
    
    def __init__(self, user_id: str):
        self.executor = ActionExecutor(user_id)
    
    async def handle_tool_calls(self, tool_calls: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Process OpenAI tool calls and return results in the expected format"""
        results = []
        
        for tool_call in tool_calls:
            try:
                # Parse the function call
                function_name = tool_call.get("function", {}).get("name")
                arguments = json.loads(tool_call.get("function", {}).get("arguments", "{}"))
                
                # Create a temporary action for execution
                action = MeetingAction(
                    id=tool_call.get("id"),
                    action_type=self._map_function_to_type(function_name),
                    description=f"Execute {function_name}",
                    details={
                        "function": function_name,
                        "arguments": arguments
                    },
                    status=ActionStatus.PENDING,
                    created_at=datetime.utcnow()
                )
                
                # Execute the action
                result = await self.executor.execute_action(action)
                
                # Format the response for OpenAI
                results.append({
                    "role": "tool",
                    "tool_call_id": tool_call.get("id"),
                    "content": json.dumps(result)
                })
                
            except Exception as e:
                results.append({
                    "role": "tool",
                    "tool_call_id": tool_call.get("id"),
                    "content": json.dumps({
                        "error": str(e),
                        "success": False
                    })
                })
        
        return results
    
    def _map_function_to_type(self, function_name: str) -> str:
        """Map function names to action types"""
        mapping = {
            "schedule_calendar_event": "calendar_event",
            "send_email": "email",
            "update_google_sheet": "sheet_update",
            "create_todo": "todo"
        }
        return mapping.get(function_name, "unknown")