"""
Meeting Bot API endpoints
"""

from fastapi import APIRouter, HTTPException, Depends
from typing import Dict, Any
from pydantic import BaseModel
from datetime import datetime

from app.core.auth import get_current_user
from app.services.meeting_bot_service import meeting_bot_orchestrator
from app.services.meet_bot import meet_bot_manager

router = APIRouter(prefix="/bot", tags=["bot"])


class CreateSessionRequest(BaseModel):
    meetUrl: str


@router.post("/create-session")
async def create_bot_session(
    request: CreateSessionRequest,
    current_user: dict = Depends(get_current_user)
):
    """Create a new meeting bot session"""
    try:
        user_id = current_user["sub"]
        print(f"Creating bot session for user: {user_id}, meet_url: {request.meetUrl}")
        
        # Create session with orchestrator
        result = await meeting_bot_orchestrator.create_and_join_meeting(
            user_id=user_id,
            meet_url=request.meetUrl
        )
        
        print(f"Bot session result: {result}")
        
        return {
            "success": True,
            "session_id": result["session_id"],
            "status": result["status"],
            "message": "Bot session created and joining meeting",
            "meet_url": request.meetUrl
        }
        
    except Exception as e:
        print(f"Error in create_bot_session: {str(e)}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Failed to create bot session: {str(e)}")


@router.get("/sessions/{session_id}")
async def get_bot_session(
    session_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Get bot session details"""
    try:
        # Get the session from memory
        session = meet_bot_manager.get_session(session_id)
        if session:
            # Session found in memory
            return {
                "id": session.session_id,
                "meetUrl": session.meet_url,
                "status": session.status,
                "startTime": session.start_time.isoformat() if session.start_time else None,
                "endTime": session.end_time.isoformat() if session.end_time else None,
                "transcript": session.transcript or "",
                "summary": session.summary or "",
                "actions": session.actions or [],
                "meetingId": session.meeting_id  # Include meeting ID
            }
        
        # Session not in memory - try to find from Firebase
        from app.services.firebase_service import firebase_service
        
        # Search for meeting with this session_id
        meeting = await firebase_service.get_meeting_by_session_id(session_id)
        if meeting:
            # Found the meeting in Firebase
            return {
                "id": session_id,
                "meetUrl": meeting.get("meet_url", ""),
                "status": "completed",  # If it's in DB, it was completed
                "startTime": meeting.get("start_time"),
                "endTime": meeting.get("end_time"),
                "transcript": meeting.get("transcript", ""),
                "summary": meeting.get("summary", ""),
                "actions": meeting.get("actions", []),
                "meetingId": meeting.get("id")  # Include meeting ID
            }
        
        raise HTTPException(status_code=404, detail="Bot session not found")
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get bot session: {str(e)}")


@router.post("/sessions/{session_id}/stop")
async def stop_bot_session(
    session_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Stop recording and process the meeting"""
    try:
        # Stop the bot session
        result = await meeting_bot_orchestrator.stop_bot_session(session_id)
        
        return {
            "success": True,
            "session_id": session_id,
            "status": result["status"],
            "transcript": result.get("transcript", ""),
            "summary": result.get("summary", ""),
            "actions": result.get("actions", []),
            "message": "Meeting recording stopped and processed"
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to stop bot session: {str(e)}")


@router.post("/sessions/{session_id}/execute-action/{action_id}")
async def execute_bot_action(
    session_id: str,
    action_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Execute a specific action generated by the bot"""
    try:
        # Get the session
        session = meet_bot_manager.get_session(session_id)
        if not session:
            raise HTTPException(status_code=404, detail="Bot session not found")
        
        # Execute the action
        result = await session.execute_action(action_id)
        
        return {
            "success": True,
            "action_id": action_id,
            "status": result["status"],
            "result": result.get("result", {}),
            "message": f"Action {action_id} executed successfully"
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to execute action: {str(e)}")